[package]
name = "programming_languages_project_Fuad_Mahmud_Shad"
version = "0.0.0"
edition = "2021"
authors = ["mahmud.shad@sa.stud.vu.lt"]

[dependencies]
# No external dependencies needed

[dev-dependencies]
# No additional dev-dependencies needed for tests